//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
        public string NewPhotoPath
        {
            get
            {
                if (string.IsNullOrEmpty(PhotoPath))
                {
                    return "res/school_logo.png";
                }
                else
                {
                    return PhotoPath;
                }
            }
        }
        public string RegistrationDateString
        {
            get
            {
                if (RegistrationDate != null)
                {
                    return RegistrationDate.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }

        public string GenderName
        {
            get
            {
                return Gender.Name;
            }
        }

        public int VisitCount
        {
            get
            {
                var datelist = ClientService.Where(p => p.ClientID == this.ID).ToList();
                return datelist.Count;
            }
        }

        public string NewBirthday
        {
            get
            {
                if (Birthday.HasValue)
                {
                    return Birthday.Value.ToShortDateString();
                }
                else
                {
                    return "";
                }
            }
        }

        public string LastDate
        {
            get
            {
                var lastService = this.ClientService.OrderByDescending(p => p.StartTime).FirstOrDefault();

                return lastService != null ? lastService.StartTime.ToShortDateString() : "нет";
            }
        }
        public DateTime? LastServiceDate
        {
            get
            {
                var lastService = this.ClientService.OrderByDescending(p => p.StartTime).FirstOrDefault();
                return lastService?.StartTime;
            }
        }
    }
}
